build:
	@echo "Building serviceD"

run:
	@echo "Running serviceD"

test:
	@echo "Testing serviceD"

clean:
	@echo "Cleaning serviceD"

deploy:
	@echo "Deploying serviceD"

publish:
	@echo "Publishing serviceD"
