build:
	@echo "Building serviceA"

run:
	@echo "Running serviceA"

test:
	@echo "Testing serviceA"

clean:
	@echo "Cleaning serviceA"

deploy:
	@echo "Deploying serviceA"

publish:
	@echo "Publishing serviceA"
