build:
	@echo "Building serviceB"

run:
	@echo "Running serviceB"

test:
	@echo "Testing serviceB"

clean:
	@echo "Cleaning serviceB"

deploy:
	@echo "Deploying serviceB"

publish:
	@echo "Publishing serviceB"
