name: Simple User Message Input

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter your custom message'
        required: true
        default: 'Hello from GitHub Actions!'
        type: string

jobs:
  generate-output:
    name: Process User Message
    runs-on: ubuntu-latest
    outputs:
      processed_message: ${{ steps.process.outputs.result }}

    steps:
      - name: Process user message
        id: process
        run: |
          USER_MESSAGE="${{ github.event.inputs.message }}"
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          PROCESSED_MESSAGE="[${TIMESTAMP}] User said: ${USER_MESSAGE}"

          echo "result=${PROCESSED_MESSAGE}" >> $GITHUB_OUTPUT
          echo "Processed message: ${PROCESSED_MESSAGE}"

  use-message:
    name: Use Message Output
    runs-on: ubuntu-latest
    needs: generate-output

    steps:
      - name: Display the message
        run: |
          echo "Received message: ${{ needs.generate-output.outputs.processed_message }}"
          echo "Message length: ${#'${{ needs.generate-output.outputs.processed_message }}'}"

      - name: Create file with message
        run: |
          echo "${{ needs.generate-output.outputs.processed_message }}" > user-message.txt
          echo "Created file with content:"
          cat user-message.txt

      - name: Upload message file
        uses: actions/upload-artifact@v4
        with:
          name: user-message-output
          path: user-message.txt
