name: Simple String Output and Input

on:
  workflow_dispatch:
    inputs:
      custom_message:
        description: 'Custom message to process'
        required: false
        default: 'Hello World'
        type: string

jobs:
  generate-output:
    name: Generate String Output
    runs-on: ubuntu-latest
    outputs:
      my_string: ${{ steps.set-output.outputs.message }}

    steps:
      - name: Set string output
        id: set-output
        run: |
          MESSAGE="${{ github.event.inputs.custom_message || 'Default message from trigger' }}"
          FORMATTED_MESSAGE="[$(date '+%Y-%m-%d %H:%M')] ${MESSAGE}"
          echo "message=${FORMATTED_MESSAGE}" >> $GITHUB_OUTPUT
          echo "Generated output: ${FORMATTED_MESSAGE}"

  use-output:
    name: Use String Input
    runs-on: ubuntu-latest
    needs: generate-output

    steps:
      - name: Use the string variable
        run: |
          echo "Received string: ${{ needs.generate-output.outputs.my_string }}"
          echo "String length: ${#'${{ needs.generate-output.outputs.my_string }}'}"
          echo "Processing complete!"
